### ISSUE TITLE
one-note.py老是报语法错误

### ISSUE THREAD

**Issue by hongyits** [cv-cat/Spider_XHS#2]
Traceback (most recent call last):
  File "d:\develop\pythonWorkspace\Spider_XHS\one-note.py", line 193, in <module>
    main()
  File "d:\develop\pythonWorkspace\Spider_XHS\one-note.py", line 188, in main
    handle_note(note_id_)
  File "d:\develop\pythonWorkspace\Spider_XHS\one-note.py", line 115, in handle_note
    ret = js.call('get_xs', '/api/sns/web/v1/feed', note_id, cookies['a1'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Python\Python311\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Python\Python311\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Python\Python311\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Python\Python311\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Python\Python311\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Python\Python311\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 语法错误

**Comment by hongyits** [comment]
好像是新电脑没安装node，没事了
