### ISSUE TITLE
search报错

### ISSUE THREAD

**Issue by rikatinghuang** [cv-cat/Spider_XHS#32]
Traceback (most recent call last):
  File "/Users/tinghuang/Spider_XHS/search.py", line 95, in <module>
    search.main(info)
  File "/Users/tinghuang/Spider_XHS/search.py", line 79, in main
    self.handle_note_info(query, number, sort, need_cover=True)
  File "/Users/tinghuang/Spider_XHS/search.py", line 55, in handle_note_info
    ret = js.call('get_xs', api, data, self.cookies['a1'])
TypeError: 'NoneType' object is not subscriptable

**Comment by cv-cat** [comment]
cookies没设置把

**Comment by iiweniiang** [comment]
> Traceback (most recent call last): File "/Users/tinghuang/Spider_XHS/search.py", line 95, in search.main(info) File "/Users/tinghuang/Spider_XHS/search.py", line 79, in main self.handle_note_info(query, number, sort, need_cover=True) File "/Users/tinghuang/Spider_XHS/search.py", line 55, in handle_note_info ret = js.call('get_xs', api, data, self.cookies['a1']) TypeError: 'NoneType' object is not subscriptable

先执行  npm i jsdom  就可以了
